# Define the system of units to use internally. 
InternalUnitSystem:
  UnitMass_in_cgs:     4.4356e+44
  UnitLength_in_cgs:   3.085e+21
  UnitVelocity_in_cgs: 9.78469e+07
  UnitCurrent_in_cgs:  1             # Amperes
  UnitTemp_in_cgs:     1             # Kelvin

# Parameters governing the time integration
TimeIntegration:
  time_begin: 0.    # The starting time of the simulation (in internal units).
  time_end:   6.0    # The end time of the simulation (in internal units).
  dt_min:     1e-10 # The minimal time-step size of the simulation (in internal units).
  dt_max:     1e-3  # The maximal time-step size of the simulation (in internal units).
  
Scheduler:
  max_top_level_cells:    8
  tasks_per_cell:  10

# Parameters governing the snapshots
Snapshots:
  basename:            snap/snapshot
  time_first:           0.00           # Time of the first output (non-cosmological run) (in internal units)
  delta_time:           0.01            # Time difference between consecutive outputs (in internal units)

# Parameters governing the conserved quantities statistics
Statistics:
  scale_factor_first:  0.01408450704 # Scale-factor of the first stat dump (cosmological run)
  time_first:          0.01 # Time of the first stat dump (non-cosmological run) (in internal units)
  delta_time:          1.05 # Time between statistics output

# Parameters for the self-gravity scheme
Gravity:
  mesh_side_length:       32
  MAC:                    geometric  # Choice of mulitpole acceptance criterion: 'adaptive' OR 'geometric'.
  eta:                    0.025     # Constant dimensionless multiplier for time integration.
  theta_cr:                  0.7       # Opening angle (Multipole acceptance criterion)
  comoving_softening:     0.01      # Comoving softening length (in internal units).
  max_physical_DM_softening: 0.01      # Physical softening length (in internal units).


# Parameters related to the initial conditions
InitialConditions:
  file_name:  plummer.hdf5
  periodic:   0
  shift: [10, 10, 10]

# This is used only for testing. By default, will have no effect (-self-gravity flag in run script)
PointMassPotential:
   position:         [10., 10., 10.]  # Location of the point mass (internal units)
   useabspos:                   1  # Use absolute positions (0 for relative to centre)
   mass:                 100  # Mass of the point (internal units)
   softening:                1.0  # Softening length (internal units)
   timestep_mult:             0.1  # (Optional) The dimensionless constant C in the time-step condition

  